# Physics 77, Lecture 2: Basics, Functions, Loops, Lists and Array

## Outline
- Address questions
- Loop back: data representation, bits and bytes
- Composite Types (Lists, tuples, arrays)
- Functions
- Conditionals
- Loops


# Recap: Week 1-2

- Introductory slides: course outline, syllabus, policy
- Introduction to Unix, including use of the command line
- A graphing teaser
- Introduction to computing, programming and python

### Association rules, order of operations

Let me address one of the issues that came up last week. 

Python follows the standard "PEMDAS" order of evaluating operators:
1. Parentheses
1. Exponentiation
1. Multiplication/division (equal precedence, evaluate from left to right)
1. Addition/subtraction (equal precedence, evaluate from left to right)

The full table (in the reverse order, i.e. from last to first) is listed here: https://docs.python.org/3/reference/expressions.html#operator-precedence

Here are some examples. The general rule -- if in doubt, add parentheses ! 

In [2]:
2+2*2**3

18

In [3]:
(2+2)*2-(1/2)**3

7.875

Here is a tricky one -- how would this be evaluated ? 

In [4]:
144.**1/2   # is this equal to sqrt(144) ?

72.0

Try again:

In [6]:
print('sqrt(144)=',144.**(1./2))  # this is OK
print('sqrt(144)=',144.**0.5)     # this is even better -- seems like a small saving of compute time, but it adds up
print(75/2.,0.5*75)

sqrt(144)= 12.0
sqrt(144)= 12.0
37.5 37.5


### Number of bytes and precision of data types

In [7]:
from decimal import Decimal
import sys

Let's determine the sizes of basic types

In [8]:
sys.getsizeof(int)  # huh ?

416

In [9]:
sys.getsizeof(int(2)) # more realistic. 8 bytes for the data, 16 bytes of overhead

28

In [10]:
sys.maxsize    # this is a 64-bit integer, because I am running a 64-bit version of Python

9223372036854775807

In [11]:
2**63-1  # check

9223372036854775807

Interesting thing about Python is that it would allocate more bytes for data if needed, so there is no practical limit to the integer value

In [14]:
print(2**65-1)
print(type(2**65-1))

36893488147419103231
<class 'int'>


In [ ]:
print(sys.getsizeof(2**65))
print(sys.int_info)

Floating point numbers:

In [16]:
sys.getsizeof(float(1.0))   # apparently, also 24 bytes

24

Largest representable float

In [20]:
1.6e+308

1.6e+308

In [23]:
x=3e+308
print(x)

inf


In [26]:
5+7/180.+1.8e308/1.8e+308

nan

Smallest representable float

In [27]:
5e-324

5e-324

In [28]:
2e-324

0.0

#### Sizes of composite data types (tuples, lists, arrays)

In [30]:
l = [1,2,4,5,6]  # 5*8=40 bytes of information
sys.getsizeof(l)

96

In [31]:
t = (1,2,4,5,6)
sys.getsizeof(t)

80

In [36]:
import numpy as np
N=10000
a = np.zeros(N,dtype=np.int16)
print(a)
print('size of a {0:d}-element array is {1:d} bytes, {2:3.1f} bytes/element'.format(N,sys.getsizeof(a),sys.getsizeof(a)/N))

[0 0 0 ... 0 0 0]
size of a 10000-element array is 20096 bytes, 2.0 bytes/element


#### Beware of floating point comparisons !

In [40]:
i = 1
print(type(i))
print(1 == i)

<class 'int'>
True


In [48]:
x = 11.00000000001/10
y = 1.1
x == y

False

In [50]:
(x-y)<1e-6   # control precision of the comparison, don't rely on automatic precision

True

In [51]:
import numpy as np

In [52]:
np.pi

3.141592653589793

In [53]:
np.pi == 3.141592653589793238462643383279502884197169399

True

In [54]:
3.14159265358979 == 3.141592653589793

False

In general, the precision of the arithmetic comparisons (==) is not guaranteed. Behavior in Python may be very different from other languages, may depend on OS, compilers, etc. It is considered bad practice to use == comparisons on floating point data. Preferably, you should check if the difference between the two numbers is within a certain precision:

In [55]:
x = 3.1415926
abs(x-np.pi)<1e-6

True

### Formatted output

Usually the data you manipulate has finite precision. You do not know it absolutely precisely, and therefore you should not report it with an arbitrary number of digits. One of the cardinal rules of a good science paper: round off all your numbers to the precision you know them (or care about) -- and no more ! 

#### Examples:

In [58]:
x = 21.3   # I only know 3 digits
print(x)   # OK, let Python handle it

21.3


That's actually pretty good -- Python remembered stored precision !
What happens if you now use x in a calculation ? 

In [59]:
print(np.sqrt(x))

4.61519230368573


Do we really know the output to 10 significant digits ? No ! So let's truncate it

In [62]:
print('sqrt(x) = {0:1.2f}'.format(np.sqrt(x)))

sqrt(x) = 4.62


Another (deprecated) way to skin this cat:

In [63]:
print('sqrt(x) = %5.2f' % np.sqrt(x))
print('sqrt(y) = %5.2f' % np.sqrt(101))

sqrt(x) =  4.62
sqrt(y) = 10.05


Print two numbers:

In [150]:
print ('sqrt(x) = {0:3.2e}, x**2 = {1:4.2f}'.format(np.sqrt(x),x**2))
print ('x**2 = {1:4.2f}, sqrt(x) = {0:3.2e}'.format(np.sqrt(x),x**2))
print ('sqrt(x) = %3.2e, x**2 = %4.2f' % (np.sqrt(x), x**2))

sqrt(x) = 4.62e+00, x**2 = 453.69
x**2 = 453.69, sqrt(x) = 4.62e+00
sqrt(x) = 4.62e+00, x**2 = 453.69


String formatting: can specify the length of the field and justification. By default, the strings are left-justified, and if the length specifier exceeds the length of the string, the string is padded by white space

In [152]:
str = 'Jones, Bill'
print('My name is {0:20s} and I like {1:s}'.format(str,'pineapples'))

My name is Jones, Bill          and I like pineapples


To change justification, use "<" to left-justify, ">" to right-justify, and "^" to center:

In [154]:
print('My name is {0:>20s} and I like {1:s}'.format(str,'pineapples'))

My name is          Jones, Bill and I like pineapples


Another cool feature of `format()` function (in Python 3) is ability to label parameters by readable names instead of numbers

In [158]:
print ('x={x:4.2f}, sqrt(x) = {sqrt:4.2f}, x**2 = {square:4.2f}'.format(x=x,sqrt=np.sqrt(x),square=x**2))

x=21.30, sqrt(x) = 4.62, x**2 = 453.69


For more formatting options, see https://pyformat.info/

A tricky example from last week. Treat '%' in the old-style formatting expression as an operator which has highest precedence. It is the operator that takes a string and another type, and returns a string. E.g. 

In [161]:
stringFormat = 'var = %5.3f'
print(stringFormat, type(stringFormat))

out = stringFormat % 2.5
print(out)
print(type(out))
print(stringFormat % 75)


var = %5.3f <class 'str'>
var = 2.500
<class 'str'>
var = 75.000


So far so good. But what if you want to do some operations inline, e.g.:

In [162]:
print('var = %5.3f' % 5./2)

TypeError: unsupported operand type(s) for /: 'str' and 'int'

This does not work, because % takes the first number (5.) and converts it to formatted string; the string cannot be divided by an integer (2)
So again, use parentheses when in doubt ! 

In [163]:
print('var = %5.3f' % (5./2))

var = 2.500


### Composite data types: lists, tuples, sets, arrays

Any computing language defines more complex data structures, which aggregate individual data into a single container. There are two built in structures to python called tuples and lists. However, for our purposes, the most useful data structure is an array, which holds a fixed number of elements of a single type, usually in a contiguous region in memory. 
Individual array elements can be indexed; first index in Python and other C-like languages is 0


In [86]:
import numpy as np
a = np.array([1,2,3,4,5,9])
print (a)
print(len(a))

[1 2 3 4 5 9]
6


In [81]:
a[1]

2

In [83]:
a[7]=10

IndexError: index 7 is out of bounds for axis 0 with size 7

In [84]:
print (a[-1], a[-3])   # beware, very different in other languages !

111 5


In [87]:
print(len(a)) # how long is an array ? 

6


In [92]:
print(a)
# append element to an array. Beware ! - leaves original array intact, and returns a new array
b = np.append(a,11)
print(a)
print(b)

[1 2 3 4 5 9]
[1 2 3 4 5 9]
[ 1  2  3  4  5  9 11]


In [ ]:
a = np.append(a,[6,7,8,9,10]) # if you want to change the original array
print (a)

Arrays can be multi-dimentional

In [147]:
m = np.ndarray(shape=(3,3),dtype=float)  # unitialized array
print (m)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [148]:
m[0,:]=[1,2,3]
m[1,:]=[4,5,6]
m[2,:]=[7,8,9]
print (m)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [97]:
print (m[0][1]) # C-style, row-wise
print (m[0,1])

2.0
2.0


In [108]:
v = np.array([1,2,3])
vt = np.transpose(v)
print(vt)

wt = np.ndarray(shape=(3,1),dtype=float)  # unitialized array
wt[0,0] = 1
wt[1,0] = 2
wt[2,0] = 3
wt[:,0] = [11,12,13]
print(wt)

[1 2 3]
[[11.]
 [12.]
 [13.]]


In [112]:
v = np.array([1,-1,10])
print(m)
print(v)
print (m*v,"\n")            # probably not what you expected ?
print (np.matmul(m,v),"\n") # this is how we do linear algebra !
#print (m*5)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[ 1 -1 10]
[[ 1. -2. 30.]
 [ 4. -5. 60.]
 [ 7. -8. 90.]] 

[29. 59. 89.] 



In [113]:
print (np.linalg.det(m))  # determinant -- remeber do not compare directly to zero !

-9.51619735392994e-16


In [114]:
abs(np.linalg.det(m)-1e-6)>0  # is matrix invertible ? 

True

Lists are a bit more flexible than an array, but does not need to consist of elements of a single type. This can be convenient, but I generally consider this a risk. So if I were you, I would keep elements of a single type in a list. You can convert lists into Numpy arrays then. 

In [116]:
mylist = [1,2,3,4,'foo','bar',5.8]
print(mylist)

[1, 2, 3, 4, 'foo', 'bar', 5.8]


In [118]:
print (len(mylist))
print(mylist[4])

7
foo


In [119]:
l = [1,2,3]
l.append([6,7]) # should append individual elements 6 and 7, right ?
print (l)           # woah, what happened ?
print (len(l))

[1, 2, 3, [6, 7]]
4


In [120]:
l.extend([8,9,10,11])    # this is what we really meant
print (l)

[1, 2, 3, [6, 7], 8, 9, 10, 11]


In [ ]:
len(l)

Differences between tuples and lists: tuples are not mutable !

In [151]:
t = (1,2,3)
print(t)
t[2] = 5
t.append(5)

(1, 2, 3)


TypeError: 'tuple' object does not support item assignment

A more powerful structure is a dictionary (map, or hash table, or RB tree in some languages)

In [132]:
age = {'Jones': 57, 'Smith': 17}   # declare a dictionary with 2 elements. Types can be mixed
print(age)
print (age['Smith'])
age['Smith'] = 45
print (age['Smith'])
age['Jones, Bill'] = 5
age['Baker, Street'] = 105
print (age['Jones'])
print (age['Jones, Bill'])
#print (age['Ivanov'])

income = {'Jones': 1}
print (income['Jones'])

{'Jones': 57, 'Smith': 17}
17
45
57
5
1


## Functions

A function is a self-contained named piece of code that can be used by other parts of the code. Functions usually take arguments (parameters, variables), and return a value. Trig functions are a standard example. Most languages allow you to define your own functions. Functions can be group into a library, usually according to functionality they provide (e.g. math, complex numbers, linear algebra, plotting, etc).

In a way, Python functions can be viewed mathematical functions:

$f: \mathbb{X} \rightarrow \mathbb{Y}$

where $\mathbb{X}$ and $\mathbb{Y}$ can be whichever space of your choice.

Python has 3 classes of functions:
-  built-in functions, e.g. print()
-  functions from packages/modules, e.g. sin() from the math package
-  user-defined functions.

**Example 1: absolute value**

$\text{abs}: \mathbb{R} \rightarrow \mathbb{R}^+_0$

Mathematical implementation:

$x = \sqrt{x^2}$

In [ ]:
x = -3
r = abs(x)   # Call the abs() function 
print(r)     # Call the print() function!

**Example 2: type casting**

In python one can convert variables from one type to the other using dedicated predefined functions. One example is the <font color=blue>float</font> function:

In [ ]:
a = 1.
b = float(a) # casting a float to a float. Actually quite useless
c = 2
d = float(c) # casting an integer to a float
e = "4."
f = float(e) # casting a string to a float
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)

### User defined functions

If the function we need doesn't exist, we can create one. In order to do so, we need to provide:
- name of the function
-  a list of arguments
-  the algorithm of the function
-  the return value

The basic structure of a function is the following:

In [ ]:
def MyFunction( x ):
    y = x*x            
    return y

print( MyFunction(3) ) 

In [ ]:
y = MyFunction(173)
print(y)
print(173**2)

Notice:
-  the colon at the end of the function declaration
-  the indentation
-  the <font color=blue>return</font> command at the end of the function body

**Example: $\sin{(x)}/x$**

In [ ]:
import matplotlib.pyplot as plt # we need this for drawing
import numpy as np              # for the sin and linspace function

def SinXoverX( x ):  # declaration
    y = np.sin(x)/x  # implementation
    return y         # return

x = np.linspace( 0.5, 100., 200 ) # generate 200 points evenly distributed between 0.5 and 100.
y = SinXoverX(x)
# if a plot function doesn't show anything, run this and then the plot function again
%matplotlib inline
plt.plot( x, y, 'r-' )

**Example: function with multiple arguments**

In [ ]:
def distance( x, y ):
    return abs(x-y) # It's a very simple calculation, so I can implement it directly in the return statement

print( distance( 2., 4. ) )

**Required and optional arguments**

Python functions can have two types of arguments: required and optional. Required arguments have no default value and must be passed by the user. Optional arguments have a default value which is used if not specified by the user.
For example, let's rewrite the <font color=blue>distance</font> function with the second argument as optional:

In [ ]:
def distance( x, y=0. ):
    return abs(x-y)

print( distance( 2., 4. ) )
print( distance( 1. ) )

**Function features to keep in mind**

-  Python allows also functions with no return value. Why? Sometimes a function is used to do things. e.g. if you want to compute the same quantity many times, and print it.
-  Functions can only be used after they are defined. It is good practice to define them at the beginning of a script.
-  You can put the function definitions in a separate file and import it. This is useful if you have some generic function that you use in many different programs.

## Conditionals

Conditionals are commands that are executed only if some condition is satisfied.
Beware! Indentation is important in Python. Note, that it doesn't really matter how broad the indentation is.


**Example: Heaviside step function**

All the functions we considered so far were well behaved. But how do we code a step function in Python?

$y = f(x) =
\begin{cases}
0 \quad \text{if}\quad x<0 \\
1 \quad \text{if}\quad x\geq0
\end{cases}
$

In [ ]:
def Theta( x ):
    if x < 0.:
        return 0.
    return 1.

xraw = input('Enter numerical value: ') # Ask the user to privide a value
print(type(xraw))   # beware ! In Python 3 this returns a string, which needs to be converted to int or float type
#x = eval(xraw)      # Also beware of potential security risks (buffer overflow)
print( Theta(float(xraw)) )

An important thing to take into account is the indentation!

In [ ]:
x=-200
if x < 0 :
    x = -x   # only executed for negative numbers
    if x < -100 : 
        print('Very small')
    print ('This was a negative value')
print (x)    # always executed

Sometimes you may want to do two different things:

In [ ]:
sum = 10
xraw = input('Enter numerical value: ')
x=float(xraw)
if x < 0 :
    sum = sum - x
else :
    sum += x
print (sum)

And sometimes you may need to have several branches

In [ ]:
value = 0 # this line is not needed
x = float(input('Enter numerical value: '))
if x > 10 :
    value = -1
elif x > 7 : # else if
    value = 6
elif x > -1 :
    value = 1
else :
    value = 0
    
print (value)

In [ ]:
## Loops

### While

The while loop repeats and execution while (as long as) a condition is valid.

In [ ]:
sum = 0
count = 0
while sum < 99:
    sum += 10
    count += 1
    print (sum)
    
print (sum, count)

**Special keywords: break, continue, pass, else**

break:

In [ ]:
sum = 0
count = 0
while sum < 100:
    sum += 10
    count += 1
    if count >= 6:
        break
    
print (sum, count)

continue:

In [ ]:
sum = 0
count = 0
while sum < 100000:
    sum += 10
    count += 1
    if count > 4 :
        continue
    print (sum)
    
print (sum, count)

else:

In [ ]:
sum = 0
count = 0
while sum < 100:
    sum += 10
    count += 1
    if count >= 60:
        break
    else:                                     # beware of indentation !!!
        print ("Finished without break")
    
    
print (sum, count)

In [ ]:
sum = 0
count = 0
while sum < 100:
    #sum -= 10       # typo ! 
    sum += 10       # fixed typo ! 
    count += 1
    print(sum)
    
print (sum, count)

## For

The for loop is more conventional and repeats the execution for an index within a given range. This is similar to for() loop in C or other languages.

An equivalent syntax in C would be for(int i=0;i<10;i++) {}

In [ ]:
list = range(0,10)
print(list)
print (len(list))

In [ ]:
for i in list:    # loop from 0 to 10, not including 10, with step = 1
    print (i, i*2)

In [ ]:
for i in range(0,10,2):   # loop from 0 to 10, not including 10, with step = 2
    print (i)

In [ ]:
list = [1,2,3,4,7,111.,67.] # iterate over elements of the tuple
list.append(12)          # what happens here ? 
for x in list:
    print (x**2)

You can iterate over lists produced by other functions, e.g. a list of keys to a dictionary 

In [ ]:
lastnames = {}                        # create a dictionary
lastnames['Billy'] = 'Jones'
lastnames['Johnny'] = 'Jones'
lastnames['Johnny'] = 'Baker'
lastnames['Heather'] = 'Gray'
#lastnames[5] = 'Foo'

#print(lastnames['Yury'])
lastnames['Yury'] = 'Kolomensky'

#list = sorted(lastnames.keys(),reverse=True)
#print (list)
for key in sorted(lastnames.keys(),reverse=True):          # iterate over elements of the dictionary
    print (key, lastnames[key])


### Nesting and recursive functions

We have seen already a few examples of an if statement inside a while loop: this called nesting. Python sets no limit to nesting, i.e. you can have infinite statements and loops within each other.

In [ ]:
def factorial(n):                # definition of the function
    value = 1
    for i in range(2,n+1):       # loop
        value *= i               # increment factorial 
        
    return value                 # return value

print ('factorial(10)=',factorial(10))
for i in range(1,5):
    print ('factorial(%d)=%2d' % (i,factorial(i)))

#print(factorial(1.1))

Here is a more elegant way to implement the function (recursive). It also has basic error handling

In [ ]:
import numpy as np
def factRecursive(n):
    '''Computes n!, input: integer, output: integer'''
    if type(n)!=int:                     # these factorials defined only for integers
        return np.nan                    # return Not-a-number
    if n > 1:
        return n*factRecursive(n-1)      # THIS IS THE RECURSION!!
    elif n >= 0:
        return 1
    else:
        return -np.inf                 # return negative infinit
    
print (factRecursive(10))
print (factRecursive(-1))
print (factRecursive('Joe'))

x = factorial(5)   # old function still defined
y = x**2
print (y)