# Introduction to Linear Algebra


In [1]:
# imports
import numpy as np
import scipy
%matplotlib inline
%precision 4

'%.4f'

## Examples: matrices, determinants

In [2]:
A = np.matrix([
    [0, 4],
    [2, 0]]
)
B = np.matrix(
    [[-1, 2],
     [1, -2]]
)

C = A + B
print("C=\n",C)
print("Determinant of C is",np.linalg.det(C))
D1 = A*B
D2 = B*A
print("D1=\n",D1)
print("D2=\n",D2)


C=
 [[-1  6]
 [ 3 -2]]
Determinant of C is -16.000000000000007
D1=
 [[ 4 -8]
 [-2  4]]
D2=
 [[ 4 -4]
 [-4  4]]


### Gauss Elimination Example 

In [3]:
M = np.matrix(
[[10,-7,0],
[-3,2.099,6],
[5,-1,5]]  
)
print(M)
print("det M =",np.linalg.det(M))


[[10.    -7.     0.   ]
 [-3.     2.099  6.   ]
 [ 5.    -1.     5.   ]]
det M = -150.05000000000007


In [4]:
Y = np.array([7,3.901,6])
Minv = np.linalg.inv(M)
print(Minv)
X = np.matmul(Minv,Y)
print('Solution with matrix inversion:\n X=',X)


[[-1.0993e-01 -2.3326e-01  2.7991e-01]
 [-2.9990e-01 -3.3322e-01  3.9987e-01]
 [ 4.9950e-02  1.6661e-01  6.6644e-05]]
Solution with matrix inversion:
 X= [[ 0. -1.  1.]]


In [5]:
X2 = np.linalg.solve(M,Y)
print("Using solver:\n X2=",X2)

Using solver:
 X2= [ 0. -1.  1.]


### LU Decomposition Example

`numpy.linalg.solve` uses LU decomposition with pivoting

In [6]:
A = np.matrix(
[
    [25,5,1],
    [64,8,1],
    [144,12,1]
])
Y = np.array([106.8,177.2,279.2])
X = np.linalg.solve(A,Y)
print("Solution: X=",X)

Solution: X= [ 0.2905 19.6905  1.0857]


In [7]:
import scipy.linalg as scl

P,L,U = scl.lu(A,permute_l=False)
print('L=\n',L)
print('U=\n',U)
print('P=\n',P)

L=
 [[1.     0.     0.    ]
 [0.1736 1.     0.    ]
 [0.4444 0.9143 1.    ]]
U=
 [[144.      12.       1.    ]
 [  0.       2.9167   0.8264]
 [  0.       0.      -0.2   ]]
P=
 [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


## Eigenvalue problem

### The eigenvalue problem ("diagonalization")

Probably the most famous problem in all of science is the eigenvalue problem. It is ubiquitous across fields and is the defining problem of quantum mechanics. In this problem, we change the problem slightly from before. For a given $A$, we try to look for scalar values $\lambda$ and vectors $v$ that satisfy the matrix equation

$$A v = \lambda v$$

Let us look at a simple example:
$$A = \begin{pmatrix}
0 & 1  \\
1 & 0 \\
\end{pmatrix}$$
The eigenvectors of this matrix are 
$$v_1 =  \frac{1}{\sqrt{2}}\begin{pmatrix}
1 \\
1 \\
\end{pmatrix}\text{ and }
v_2 = \frac{1}{\sqrt{2}}\begin{pmatrix}
1 \\
-1 \\
\end{pmatrix}$$
If you multiply $A$ by $v_1$ you get $Av_1 = v_1$ and if you multiply $A$ by $v_2$ you get $Av_2 = -v_2$ (check these for yourself by doing the multiplications). This means that the eigenvalue $\lambda_1$ corresponding to the eigenvector $v_1$ is $\lambda_1 = 1$, and the eigenvalue $\lambda_2$ corresponding to the eigenvector $v_2$ is $\lambda_2 = -1$.

One geometric intuition for what an eigenvector is that it is a vector whose direction is not changed by the action of $A$: only its length is rescaled by a factor of $\lambda$. 

An $m \times m$ matrix can have at most $m$ eigenvectors (and consequently it can have at most $m$ unique eigenvalues). It can also have $m$ eigenvectors but fewer than $m$ eigenvalues--that is, multiple eigenvectors may have the same eigenvalue (in physics, this is called "degeneracy").

This problem is referred to as "diagonalization" because once you have found all of the eigenvectors $v_i$ and their eigenvalues $\lambda_i$, you can decompose $A$ as
$$A = U D U^\dagger$$
where 
$$ D = \begin{pmatrix}
\lambda_1 & 0 & \cdots & 0 & 0 \\
0 & \lambda_2 & \cdots & 0 & 0 \\
\vdots & \vdots & \ddots & \vdots & \vdots\\
0 & 0 & 0 & \lambda_{m-1} & 0 \\
0 & 0 & \cdots & 0 & \lambda_m \\
\end{pmatrix}$$
and the columns of $U$ are formed by
$$U = \begin{pmatrix}
v_1 & v_2 & \cdots & v_{m-1} & v_m
\end{pmatrix}$$
(remember each $v_i$ is a column of $m$ elements). And $U^\dagger$ denotes the conjugate transpose of $U$. $D$ is a "diagonal" matrix becaues it has non-zero elements only along its diagonal, so this process is called "diagonalization".

It turns out that the determinant of a matrix, defined above, is also equal to the product of its eigenvalues.
$$\det(A) = \lambda_1 \times \lambda_2 \dots \times \lambda_m$$
So when $\det(A) = 0$ (the matrix is *singular*), this means that at least one eigenvalue is equal to zero.

### Finding eigenvectors and eigenvalues with numpy

In [8]:
w,v = np.linalg.eig(A)
print('Eigenvalues of A=',w)
print('Eigenvectors: \n',v)

Eigenvalues of A= [40.0196 -6.3501  0.3305]
Eigenvectors: 
 [[-0.2022 -0.0696  0.0195]
 [-0.4317  0.2432 -0.2879]
 [-0.8791  0.9675  0.9575]]


In [9]:
S = np.matrix(
[
    [0,1],
    [1,0]
])
w,v = np.linalg.eig(S)
print('Eigenvalues of S=',w)
print('Eigenvectors: \n',v)

Eigenvalues of S= [ 1. -1.]
Eigenvectors: 
 [[ 0.7071 -0.7071]
 [ 0.7071  0.7071]]


In [10]:
# For this matrix, there is only one eigenspace, and it is one-dimensional!
# There does not exist a basis of eigenvectors!
S = np.matrix(
[
    [0,1],
    [0,0]
])
w,v = np.linalg.eig(S)
print('Eigenvalues of S=',w)
print('Eigenvectors: \n',v)

Eigenvalues of S= [0. 0.]
Eigenvectors: 
 [[ 1.0000e+000 -1.0000e+000]
 [ 0.0000e+000  2.0042e-292]]
